name: CI
on:
  push:
    branches:
      - main
      - pull_request
jobs:
  job1:
    runs-on: self-hosted
    name: build example and deploy to minikube locally
    steps:
    - uses: actions/checkout@v3
    - name: Start minikube
      id: minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t local/example .
        echo -n "verifying images:"
        docker images        
    - name: Deploy to minikube
      run:
        kubectl apply -f deploy-to-minikube.yaml
    - name: Test service URLs
      run: |
        minikube service list
        minikube service example --url
        echo "------------------opening the service------------------"
        curl $(minikube service example --url)        
